# -*- coding: utf-8 -*-
"""
 Inverter Modbus Register Map
Protocol: custom
Function Code: FC03  |  MPPT: 4  |  Strings: 8
IV Scan: No  |  DER-AVM: Yes  |  DEA-AVM Monitor: Yes

Auto-generated by UDP RTU Model Maker v1.3.0 - Stage 3 Pipeline
Date: 2026-03-31 15:29:55

Stage 3 source: goodwe_modbus_protocol_registers_mapping.xlsx
"""

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))

class RegisterMap:
    """ Modbus Register Map"""

    # ------------------------------------------------------------
    # Inverter Parameters (Setup)
    # ------------------------------------------------------------
    RECONNECT_TIME                                     = 0x0001   # U16
    GRID_R_VOLTAGE                                     = 0x0002   # U16
    GRID_FREQUENCY                                     = 0x0004   # U16
    DEVICE_RTC_TIME_YEAR_MONTH                         = 0x0010   # U16
    DEVICE_RTC_TIME_DAY_HOUR                           = 0x0011   # U16
    DEVICE_RTC_TIME_MINUTE_SECOND                      = 0x0012   # U16

    # ------------------------------------------------------------
    # Control Parameters
    # ------------------------------------------------------------
    REACTIVE_POWER_SET                                 = 0x0100   # U16
    DEA_TOTAL_REACTIVE_POWER_LOW                       = 0x0104   # U32
    EXPORT_POWER_LIMIT_ADJUST_RANGE                    = 0x0106   # S16
    TAI_WAN_SAFETY_VPSET                               = 0x0107   # U16
    TAI_WAN_SAFETY_PF_ADJUST                           = 0x0108   # U16
    EXPORT_POWER_LIMIT_COMMUNICATION_OVERTIME_SET      = 0x010B   # U16
    POWER_ON_ALLOW_ON_GRID_SELF_TEST                   = 0x0120   # U16
    POWER_OFF_NOT_ALLOW_ON_GRID_SELF_TEST              = 0x0121   # U16
    RESTART                                            = 0x0122   # U16
    SET_THE_EXPORT_POWER_PERCENTAGE_NEE_D_TO_TURN_ON_THE_LIMIT_SWITCH = 0x0124   # U16
    SET_THE_EXPORT_POWER_PERCENTAGE_NO_NEED_TO_TURN_ON_THE_LIMIT_SWITCH = 0x0125   # U16
    DEA_TOTAL_REACTIVE_POWER_HIGH                      = 0x0131   # U32
    BATTERY_MODE_SWITCH_BRAZIL                         = 0x0133   # U16
    SHADOW_MODE_SWITCH                                 = 0x0138   # U16

    # ------------------------------------------------------------
    # Device Information (System Info)
    # ------------------------------------------------------------
    SERIAL_NUMBER                                      = 0x0200   # string
    DEVICE_MODEL                                       = 0x0210   # string
    ERROR_CODE1                                        = 0x0220   # U32
    HIGH_BYTE_OF_TOTAL_FEED_POWER_TO_GRID_TOTAL_POWER_GENERATION = 0x0222   # U16
    LOW_BYTE_OF_TOTAL_FEED_POWER_TO_GRID_TOTAL_POWER_GENERATION = 0x0223   # U16
    HIGH_BYTE_OF_TOTAL_FEEDING_HOURS_HOURLY_POWER_GENERATION = 0x0224   # U16
    LOW_BYTE_OF_TOTAL_FEEDING_HOURS_HOURLY_POWER_GENERATION = 0x0225   # U16
    PV1_VOLTAGE                                        = 0x0226   # U16
    PV2_VOLTAGE                                        = 0x0227   # U16
    PV1_CURRENT                                        = 0x0228   # U16
    PV2_CURRENT                                        = 0x0229   # U16
    S_PHASE_VOLTAGE                                    = 0x022A   # U16
    S_PHASE_CURRENT                                    = 0x022D   # U16
    L1_FREQUENCY                                       = 0x0230   # U16
    L2_FREQUENCY                                       = 0x0231   # U16
    L3_FREQUENCY                                       = 0x0232   # U16
    PAC_L_INVERTER_CURRENT_OUTPUT_POWER                = 0x0233   # U16
    WORKING_MODE                                       = 0x0234   # U16
    INTERNAL_TEMP                                      = 0x0235   # U16
    E_DAY_DAILY_POWER_GENERATION                       = 0x0236   # U16

    # ------------------------------------------------------------
    # Inverter Realtime Data
    # ------------------------------------------------------------
    ERROR_CODE2_HIGH                                   = 0x0310   # U16
    DSP_ERROR_CODE_L                                   = 0x0311   # U16
    FIRMWARE_VERSION                                   = 0x0316   # U16
    RSVD                                               = 0x0318   # U16
    RUNNING_STATUS                                     = 0x0319   # U16
    BUS_VOLTAGE                                        = 0x031C   # U16
    FAULT_CODE_1                                       = 0x031F   # U16
    FEED_POWER_TO_GRID_IN_TODAY_DAILY_POWER            = 0x0320   # U16
    PV5_VOLTAGE                                        = 0x0324   # U16
    PV5_CURRENT                                        = 0x0325   # U16
    PV6_VOLTAGE                                        = 0x0326   # U16
    PV6_CURRENT                                        = 0x0327   # U16
    ACTIVE_POWER                                       = 0x033C   # U16
    MANUFACTURE_ID                                     = 0x033E   # U16
    WIRELESS_SIGNAL_STRENGTH                           = 0x033F   # U16
    HIGH_BYTE_OF_PV_MODE_SMT_ONLY                      = 0x0340   # U16
    LOW_BYTE_OF_PV_MODE_SMT_ONLY                       = 0x0341   # U16
    OPERATION_MODE                                     = 0x0355   # U16
    PV3_VOLTAGE                                        = 0x0357   # U16
    PV4_VOLTAGE                                        = 0x0358   # U16
    PV3_CURRENT                                        = 0x0359   # U16
    PV4_CURRENT                                        = 0x035A   # U16
    STRING1_CURRENT                                    = 0x035B   # U16
    STRING2_CURRENT                                    = 0x035C   # U16
    STRING3_CURRENT                                    = 0x035D   # U16
    STRING4_CURRENT                                    = 0x035E   # U16
    STRING5_CURRENT                                    = 0x035F   # U16
    STRING6_CURRENT                                    = 0x0360   # U16
    STRING7_CURRENT                                    = 0x0361   # U16
    STRING8_CURRENT                                    = 0x0362   # U16
    OUTPUT_CONTROL_STATE                               = 0x0370   # U16
    POWER_FACTOR                                       = 0x0376   # U16
    GRID_TOTAL_REACTIVE_POWER_LOW                      = 0x037D   # U16
    REACTIVE_POWER                                     = 0x037E   # U16
    ISO_DETECTION_VALUE                                = 0x037F   # U16
    DEA_L1_CURRENT_LOW                                 = 0x0380   # U16
    R_PHASE_CURRENT                                    = 0x03E8   # U32
    T_PHASE_CURRENT                                    = 0x03EC   # U32
    FREQUENCY                                          = 0x03FA   # U32
    DEA_STATUS_FLAG_LOW                                = 0x03FC   # U32
    PF                                                 = 0x07D0   # S16

    # ------------------------------------------------------------
    # DER-AVM Control
    # ------------------------------------------------------------
    DER_POWER_FACTOR_SET                               = 0x07D0   # Power factor setpoint [-1000,-800],[800,1000]
    DER_ACTION_MODE                                    = 0x07D1   # Action mode: 0=Self, 2=DER-AVM, 5=Q(V)
    DER_REACTIVE_POWER_PCT                             = 0x07D2   # Reactive power % [-484,484]
    DER_ACTIVE_POWER_PCT                               = 0x07D3   # Active power % [0,1100]
    INVERTER_ON_OFF                                    = 0x0834   # On/Off control: 0=ON, 1=OFF
    CLEAR_PV_INSULATION_WARNING                        = 0x0835   # Clear PV insulation warning: 1=Clear
    INVERTER_CONTROL                                   = 0x6001   # Inverter control: 0=Power on, 1=Shut down
    IV_CURVE_SCAN                                      = 0x600D   # IV curve scan: W 0=Stop,1=Start; R 0=Idle,1=Running,2=Finished
    POWER_FACTOR_DYNAMIC                               = 0x600F   # Dynamic power factor control
    REACTIVE_POWER_DYNAMIC                             = 0x6010   # Dynamic reactive power control (%)
    POWER_DERATING_PCT                                 = 0x3005   # Active power derating [0-110]%

    # ------------------------------------------------------------
    # DEA-AVM Monitor
    # ------------------------------------------------------------
    DEA_L1_CURRENT_HIGH                                = 0x03E9   # DEA L1 current (high word)
    DEA_L2_CURRENT_LOW                                 = 0x03EA   # DEA L2 current (low word)
    DEA_L2_CURRENT_HIGH                                = 0x03EB   # DEA L2 current (high word)
    DEA_L3_CURRENT_LOW                                 = 0x03EC   # DEA L3 current (low word)
    DEA_L3_CURRENT_HIGH                                = 0x03ED   # DEA L3 current (high word)
    DEA_L1_VOLTAGE_LOW                                 = 0x03EE   # DEA L1 voltage (low word)
    DEA_L1_VOLTAGE_HIGH                                = 0x03EF   # DEA L1 voltage (high word)
    DEA_L2_VOLTAGE_LOW                                 = 0x03F0   # DEA L2 voltage (low word)
    DEA_L2_VOLTAGE_HIGH                                = 0x03F1   # DEA L2 voltage (high word)
    DEA_L3_VOLTAGE_LOW                                 = 0x03F2   # DEA L3 voltage (low word)
    DEA_L3_VOLTAGE_HIGH                                = 0x03F3   # DEA L3 voltage (high word)
    DEA_TOTAL_ACTIVE_POWER_LOW                         = 0x03F4   # DEA total active power (low word)
    DEA_TOTAL_ACTIVE_POWER_HIGH                        = 0x03F5   # DEA total active power (high word)
    DEA_POWER_FACTOR_LOW                               = 0x03F8   # DEA power factor (low word)
    DEA_POWER_FACTOR_HIGH                              = 0x03F9   # DEA power factor (high word)
    DEA_FREQUENCY_LOW                                  = 0x03FA   # DEA frequency (low word)
    DEA_FREQUENCY_HIGH                                 = 0x03FB   # DEA frequency (high word)
    DEA_STATUS_FLAG_HIGH                               = 0x03FD   # DEA status flag (high word)

    # DER-AVM aliases (backward compatibility)
    POWER_FACTOR_SET   = DER_POWER_FACTOR_SET
    OPERATION_MODE     = DER_ACTION_MODE
    REACTIVE_POWER_PCT = DER_REACTIVE_POWER_PCT
    ACTIVE_POWER_PCT   = DER_ACTIVE_POWER_PCT
    ON_OFF_CONTROL     = INVERTER_ON_OFF

    # Compatibility aliases (auto-generated)
    L1_VOLTAGE                               = GRID_R_VOLTAGE
    L2_VOLTAGE                               = S_PHASE_VOLTAGE
    L1_CURRENT                               = R_PHASE_CURRENT
    L2_CURRENT                               = S_PHASE_CURRENT
    L3_CURRENT                               = T_PHASE_CURRENT
    TOTAL_ENERGY_LOW                         = HIGH_BYTE_OF_TOTAL_FEED_POWER_TO_GRID_TOTAL_POWER_GENERATION
    TODAY_ENERGY_LOW                         = E_DAY_DAILY_POWER_GENERATION
    MPPT1_VOLTAGE                            = PV1_VOLTAGE
    MPPT1_CURRENT                            = PV1_CURRENT
    INVERTER_MODE                            = RUNNING_STATUS
    GRID_TOTAL_ACTIVE_POWER_LOW              = ACTIVE_POWER


SCALE = {
    'voltage':      0.1,
    'current':      0.01,
    'power':        0.1,
    'frequency':    0.01,
    'power_factor': 0.001,
    'dea_current':          0.1,
    'dea_voltage':          0.1,
    'dea_active_power':     0.1,
    'dea_reactive_power':   1,
    'dea_frequency':        0.1,
}

DATA_TYPES = {
    'RECONNECT_TIME': 'U16',
    'GRID_R_VOLTAGE': 'U16',
    'GRID_FREQUENCY': 'U16',
    'DEVICE_RTC_TIME_YEAR_MONTH': 'U16',
    'DEVICE_RTC_TIME_DAY_HOUR': 'U16',
    'DEVICE_RTC_TIME_MINUTE_SECOND': 'U16',
    'REACTIVE_POWER_SET': 'U16',
    'DEA_TOTAL_REACTIVE_POWER_LOW': 'U32',
    'EXPORT_POWER_LIMIT_ADJUST_RANGE': 'S16',
    'TAI_WAN_SAFETY_VPSET': 'U16',
    'TAI_WAN_SAFETY_PF_ADJUST': 'U16',
    'EXPORT_POWER_LIMIT_COMMUNICATION_OVERTIME_SET': 'U16',
    'POWER_ON_ALLOW_ON_GRID_SELF_TEST': 'U16',
    'POWER_OFF_NOT_ALLOW_ON_GRID_SELF_TEST': 'U16',
    'RESTART': 'U16',
    'SET_THE_EXPORT_POWER_PERCENTAGE_NEE_D_TO_TURN_ON_THE_LIMIT_SWITCH': 'U16',
    'SET_THE_EXPORT_POWER_PERCENTAGE_NO_NEED_TO_TURN_ON_THE_LIMIT_SWITCH': 'U16',
    'DEA_TOTAL_REACTIVE_POWER_HIGH': 'U32',
    'BATTERY_MODE_SWITCH_BRAZIL': 'U16',
    'SHADOW_MODE_SWITCH': 'U16',
    'ERROR_CODE1': 'U32',
    'HIGH_BYTE_OF_TOTAL_FEED_POWER_TO_GRID_TOTAL_POWER_GENERATION': 'U16',
    'LOW_BYTE_OF_TOTAL_FEED_POWER_TO_GRID_TOTAL_POWER_GENERATION': 'U16',
    'HIGH_BYTE_OF_TOTAL_FEEDING_HOURS_HOURLY_POWER_GENERATION': 'U16',
    'LOW_BYTE_OF_TOTAL_FEEDING_HOURS_HOURLY_POWER_GENERATION': 'U16',
    'PV1_VOLTAGE': 'U16',
    'PV2_VOLTAGE': 'U16',
    'PV1_CURRENT': 'U16',
    'PV2_CURRENT': 'U16',
    'S_PHASE_VOLTAGE': 'U16',
    'S_PHASE_CURRENT': 'U16',
    'L1_FREQUENCY': 'U16',
    'L2_FREQUENCY': 'U16',
    'L3_FREQUENCY': 'U16',
    'PAC_L_INVERTER_CURRENT_OUTPUT_POWER': 'U16',
    'WORKING_MODE': 'U16',
    'INTERNAL_TEMP': 'U16',
    'E_DAY_DAILY_POWER_GENERATION': 'U16',
    'ERROR_CODE2_HIGH': 'U16',
    'DSP_ERROR_CODE_L': 'U16',
    'FIRMWARE_VERSION': 'U16',
    'RSVD': 'U16',
    'RUNNING_STATUS': 'U16',
    'BUS_VOLTAGE': 'U16',
    'FAULT_CODE_1': 'U16',
    'FEED_POWER_TO_GRID_IN_TODAY_DAILY_POWER': 'U16',
    'PV5_VOLTAGE': 'U16',
    'PV5_CURRENT': 'U16',
    'PV6_VOLTAGE': 'U16',
    'PV6_CURRENT': 'U16',
    'ACTIVE_POWER': 'U16',
    'MANUFACTURE_ID': 'U16',
    'WIRELESS_SIGNAL_STRENGTH': 'U16',
    'HIGH_BYTE_OF_PV_MODE_SMT_ONLY': 'U16',
    'LOW_BYTE_OF_PV_MODE_SMT_ONLY': 'U16',
    'OPERATION_MODE': 'U16',
    'PV3_VOLTAGE': 'U16',
    'PV4_VOLTAGE': 'U16',
    'PV3_CURRENT': 'U16',
    'PV4_CURRENT': 'U16',
    'STRING1_CURRENT': 'U16',
    'STRING2_CURRENT': 'U16',
    'STRING3_CURRENT': 'U16',
    'STRING4_CURRENT': 'U16',
    'STRING5_CURRENT': 'U16',
    'STRING6_CURRENT': 'U16',
    'STRING7_CURRENT': 'U16',
    'STRING8_CURRENT': 'U16',
    'OUTPUT_CONTROL_STATE': 'U16',
    'POWER_FACTOR': 'U16',
    'GRID_TOTAL_REACTIVE_POWER_LOW': 'U16',
    'REACTIVE_POWER': 'U16',
    'ISO_DETECTION_VALUE': 'U16',
    'DEA_L1_CURRENT_LOW': 'U16',
    'R_PHASE_CURRENT': 'U32',
    'T_PHASE_CURRENT': 'U32',
    'FREQUENCY': 'U32',
    'DEA_STATUS_FLAG_LOW': 'U32',
    'PF': 'S16',
    'DER_POWER_FACTOR_SET': 'S16',
    'DER_ACTION_MODE': 'U16',
    'DER_REACTIVE_POWER_PCT': 'S16',
    'DER_ACTIVE_POWER_PCT': 'U16',
    'INVERTER_ON_OFF': 'U16',
    'CLEAR_PV_INSULATION_WARNING': 'U16',
    'INVERTER_CONTROL': 'U16',
    'IV_CURVE_SCAN': 'U16',
    'POWER_FACTOR_DYNAMIC': 'S16',
    'REACTIVE_POWER_DYNAMIC': 'S16',
    'POWER_DERATING_PCT': 'U16',
    'DEA_L1_CURRENT_HIGH': 'S32',
    'DEA_L2_CURRENT_LOW': 'S32',
    'DEA_L2_CURRENT_HIGH': 'S32',
    'DEA_L3_CURRENT_LOW': 'S32',
    'DEA_L3_CURRENT_HIGH': 'S32',
    'DEA_L1_VOLTAGE_LOW': 'S32',
    'DEA_L1_VOLTAGE_HIGH': 'S32',
    'DEA_L2_VOLTAGE_LOW': 'S32',
    'DEA_L2_VOLTAGE_HIGH': 'S32',
    'DEA_L3_VOLTAGE_LOW': 'S32',
    'DEA_L3_VOLTAGE_HIGH': 'S32',
    'DEA_TOTAL_ACTIVE_POWER_LOW': 'S32',
    'DEA_TOTAL_ACTIVE_POWER_HIGH': 'S32',
    'DEA_POWER_FACTOR_LOW': 'S32',
    'DEA_POWER_FACTOR_HIGH': 'S32',
    'DEA_FREQUENCY_LOW': 'S32',
    'DEA_FREQUENCY_HIGH': 'S32',
    'DEA_STATUS_FLAG_HIGH': 'S32',
}

class InverterMode:
    """Inverter operating mode codes (register 0x101D)."""
    INITIAL  = 0x00  # Initial mode
    STANDBY  = 0x01  # Standby mode
    ON_GRID  = 0x03  # On-Grid mode (grid-connected)
    OFF_GRID = 0x04  # Off-Grid mode (island)
    FAULT    = 0x05  # Fault mode
    SHUTDOWN = 0x09  # Shutdown mode

    _MAP = {
        0x00: 'Initial',
        0x01: 'Standby',
        0x03: 'On-Grid',
        0x04: 'Off-Grid',
        0x05: 'Fault',
        0x09: 'Shutdown',
    }

    @classmethod
    def to_string(cls, value):
        return cls._MAP.get(int(value) if value is not None else -1,
                            f'Unknown({value})')

class StatusConverter:
    """Convert raw inverter status code to InverterMode."""

    _RAW_TO_MODE = {
        0: -1,  # Unknown
        3: -1,  # Unknown
    }

    @classmethod
    def to_inverter_mode(cls, raw_value):
        if raw_value is None:
            return InverterMode.FAULT
        mapped = cls._RAW_TO_MODE.get(int(raw_value), -1)
        if mapped >= 0:
            return mapped
        # Fallback: pass-through for known Solarize mode codes
        v = int(raw_value)
        return v if v in (0x00, 0x01, 0x03, 0x04, 0x05, 0x09) else InverterMode.FAULT

def registers_to_u32(low, high):
    """Combine two U16 registers (low-word, high-word) into U32."""
    return ((int(high) & 0xFFFF) << 16) | (int(low) & 0xFFFF)

def registers_to_s32(low, high):
    """Combine two U16 registers (low-word, high-word) into signed S32."""
    u = registers_to_u32(low, high)
    return u - 0x100000000 if u >= 0x80000000 else u

def get_mppt_registers(mppt_index):
    """Return (voltage_addr, current_addr, power_low_addr, power_high_addr) for MPPT channel."""
    if not (1 <= mppt_index <= 4):
        raise ValueError(f'MPPT index {mppt_index} out of range [1, 4]')
    r = RegisterMap
    v_name  = f'MPPT{mppt_index}_VOLTAGE'
    i_name  = f'MPPT{mppt_index}_CURRENT'
    pl_name = f'MPPT{mppt_index}_POWER_LOW'
    ph_name = f'MPPT{mppt_index}_POWER_HIGH'
    return (
        getattr(r, v_name,  None),
        getattr(r, i_name,  None),
        getattr(r, pl_name, None),
        getattr(r, ph_name, None),
    )

def get_string_registers(string_index):
    """Return (voltage_addr, current_addr) for PV string channel."""
    if not (1 <= string_index <= 8):
        raise ValueError(f'String index {string_index} out of range [1, 8]')
    r = RegisterMap
    v_name = f'STRING{string_index}_VOLTAGE'
    i_name = f'STRING{string_index}_CURRENT'
    return (
        getattr(r, v_name, None),
        getattr(r, i_name, None),
    )

